### ISSUE TITLE
Might need updates

### ISSUE THREAD

**Issue by telegraham** [learn-co-curriculum/module-assessments#2]
"For the first assessment, you'll receive two repos with instructions and deliverables."

^ Is this true? To my knowledge, it's one repo.

"It should take you no more than 90 minutes to complete the assessment." 

^ Is this true? I think it's 60 now.

"It's an open-book, totally Googleable asessment."

^ Except for old code, right?

**Comment by maxwellbenton** [comment]
Hey @telegraham,

Closing this as I think the changes you made that were merged in shortly after address these.
